# Generated by Django 4.2.11 on 2025-01-28 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125, verbose_name='title')),
                ('code', models.CharField(max_length=5, unique=True, verbose_name='code')),
                ('details', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('HIG', 'High'), ('MED', 'Medium'), ('LOW', 'Low')], default='MED', max_length=3, verbose_name='priority')),
                ('event_type', models.CharField(choices=[('OTH', 'Other'), ('WED', 'Wedding'), ('BTP', 'Birthday Party'), ('GRA', 'Graduation')], default='OTH', max_length=3, verbose_name='event type')),
                ('status', models.CharField(choices=[('CON', 'Consulation'), ('PLA', 'Planning'), ('DON', 'Done')], default='CON', max_length=3, verbose_name='status')),
                ('bill', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='bill')),
                ('bill_status', models.CharField(choices=[('UNS', 'Unsettled'), ('IVS', 'Invoice sent'), ('SET', 'Settled')], default='UNS', max_length=3, verbose_name='bill status')),
                ('date_time', models.DateTimeField(null=True)),
                ('duration', models.DurationField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', related_query_name='event', to='client.clientprofile')),
                ('coordinator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', related_query_name='event', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.CharField(max_length=125, verbose_name='details')),
                ('status', models.CharField(choices=[('NDN', 'Not done'), ('INP', 'In progress'), ('DON', 'Done')], default='NDN', max_length=3, verbose_name='status')),
                ('priority', models.CharField(choices=[('HIG', 'High'), ('MED', 'Medium'), ('LOW', 'Low')], default='MED', max_length=3, verbose_name='priority')),
                ('due_date', models.DateTimeField(null=True, verbose_name='due date')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', related_query_name='task', to='event.event')),
            ],
        ),
    ]
