# Generated by Django 4.2.11 on 2025-01-28 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClientProfile',
            new_name='Client',
        ),
    ]
